ame: Terraform - deploy VM Linux to PROD environement

trigger: none

resources:
  pipelines:
  - pipeline: pipeline-test-terraform # Name of the pipeline resource.
    source: pipeline-test-terraform # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run pipeline when any run of pipeline-poc-terraform completes

variables:
  - group: Terraform_SP
  - name: rootFolder
    value: './'
  - name: backendfile
    value: 'prod.tfstate'
  - name: tfvarsFile
    value: 'terraform.prod.tfvars'
  - name: environment
    value: 'PRD'

stages:
- template: templates/terraform-deploy-template.yml
  parameters:
    rootFolder: $(rootFolder)
    backendfile: $(backendfile)
    tfvarsFile: $(tfvarsFile)
    environment: $(environment)