name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}    
      TF_BACKEND_FILE: ${{ secrets.TF_BACKEND_FILE }}
      TF_VARS_FILE: ${{ secrets.TF_VARS_FILE }}    
    runs-on: ubuntu-latest
    environment: test

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Initialize Terraform
      run: terraform init -backend-config "key=${TF_BACKEND_FILE}" -reconfigure

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -var-file "${TF_VARS_FILE}" -input=false

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var-file "${TF_VARS_FILE}" -auto-approve -input=false

    - name: Save Terraform Outputs
      id: outputs
      run: terraform output -json > terraform_outputs.json

    - name: Upload Terraform Outputs
      uses: actions/upload-artifact@v3
      with:
        name: terraform-outputs
        path: terraform_outputs.json